# Generated by Django 5.0.4 on 2024-04-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
